version: '3.5'
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/amrakibe/goinfre/amrakibe/srcs_db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /Users/amrakibe/goinfre/amrakibe/srcs_wp
      o: bind
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      -  db:/var/lib/mysql
    ports:
      - 3306
    networks:
      - Inception
    env_file:
      - .env
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - 9000
    networks:
      - Inception
  nginx:
    image: nginx
    container_name : nginx
    build: ./requirements/nginx/.
    volumes:
    - wp:/var/www/html
    depends_on:
    - wordpress
    ports:
    - 443:443
    networks:
      - Inception
networks:
  Inception:
    driver: bridge
      
#step 1 creat a networks :> step 2 creat a volumse an check if is existe
