version: '3.5'
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/amrakibe/data/srcs_db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/amrakibe/data/srcs_wp
      o: bind
services:
  mariadb:
    image: mariadb:1337
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      -  db:/var/lib/mysql
    ports:
      - 3306
    networks:
      - Inception
    env_file:
      - .env
  wordpress:
    image: wordpress:1337
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - 9000
    networks:
      - Inception
  nginx:
    image: nginx:1337
    container_name : nginx
    build: ./requirements/nginx/.
    volumes:
    - wp:/var/www/html
    depends_on:
    - wordpress
    ports:
    - 443:443
    networks:
      - Inception
  website:
    image: website:1337
    container_name: website
    build: ./requirements/bonus/website/.
    ports:
      - 8080:8080
    networks:
      - Inception
  adminer:
    image: adminer:1337
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    ports:
      - 5000
    networks:
      - Inception
networks:
  Inception:
    name: Inception
    driver: bridge

#step 1 creat a networks :> step 2 creat a volumse an check if is existe
